# name: ci

# on:
#   push:

# jobs:
#   docker:
#     runs-on: ubuntu-latest
#     steps:
#       -
#         name: Set up QEMU
#         uses: docker/setup-qemu-action@v3
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v3
#       -
#         name: Login to Docker Hub
#         uses: docker/login-action@v3
#         with:
#           username: am2501
#           password: Yakei39ra
#       -
#         name: Build and push
#         uses: docker/build-push-action@v6
#         with:
#           file: Dockerfile
#           push: true
#           tags: sa-k-ra/stady_test:latest

# name: Pentest with Docker

# on:
#   push:
#     branches:
#       - main

# jobs:
#   pentest:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v4

#       - name: Run Kali Linux Docker Container
#         uses: docker://kalilinux/kali-rolling
#         with:
#           usage: |
#             apt install -y kali-linux-default
#           args: |
#             bash -c 
#             nmap -sV -T4 127.0.0.1:8000

name: Pentest with Docker

on:
  push:
    branches:
      - main
      - test

jobs:
  pentest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python # ワークフローのセクションごとに設定する名前。特に設定する必要はないが、どこでエラーが起きているかを把握する為にも設定しておいた方が良い。
        uses: actions/setup-python@v2 # Pythonのセットアップ
        with:
          python-version: "3.12" # Pythonのバージョン指定
      
      - name: Install Python dependencies
        run: |
          python3 -m venv Djangos
          .\Djangos\Scripts\activate
          pip install django
          python3 manage.py runserver
      

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Run Kali Linux Docker Container
        run: |
          docker run --rm -e DEBIAN_FRONTEND=noninteractive kalilinux/kali-rolling /bin/bash -c "
          apt update && \
          apt install -y kali-linux-default && \
          nmap -sV -T4 127.0.0.1:8000"
